### ISSUE TITLE
'abort' was not declared in this scope

### ISSUE THREAD

**Issue by bill538** [captainigloo/spark-web-embd-rest-json#1]
Veryfing code using this library in Particle Build fails with this error:

```
spark-web-embd-rest-json/HttpRequest.cpp:61:15: error: 'abort' was not declared in this scope
         abort()
```

**Comment by bill538** [comment]
The library will not compile on its own or with my code.

**Comment by bill538** [comment]
See fork https://github.com/bill538/spark-web-embd-rest-json for code fix.  Need to add missing headers 
#include <cstdio>
#include <stdio.h>      /\* fopen, fputs, fclose, stderr _/
#include <stdlib.h>     /_ abort, NULL */
